---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())

```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values (slide 21)
ratings %>%
  group_by(rating) %>%
  ggplot() +
  geom_bar(aes(x = rating)) +
  scale_y_continuous(label=comma)
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group
ratings %>%
  group_by(movie_id) %>%
  summarize(num_ratings = n(), avg_rating = mean(rating))
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
#ratings %>%
#  group_by(movie_id) %>%
#  summarize(num_movies = n()) %>%
#  mutate(rank = rank(-num_movies, ties.method = "first")) %>%
#  ggplot() +
#  geom_bar(aes(x = rank, y = num_movies), stat="identity")

ratings %>%
  group_by(movie_id) %>%
  summarize(num_movies = n()) 
  ggplot() +
  geom_histogram(aes(x = num_movies)) +
  scale_x_log10()

```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie (slide 23)
# hint: try geom_histogram and geom_density
ratings %>%
  group_by(movie_id) %>%
  summarize(mean_rating = mean(rating)) %>%
  group_by(mean_rating) %>%
  ggplot() +
  geom_density(aes(x = mean_rating), fill="black")

```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves (slide 25)
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity
ratings %>%
  group_by(movie_id) %>%
  summarize(num_movies = n()) %>%
  mutate(rank = rank(-num_movies, ties.method = "first")) %>%
  arrange(rank) %>%
  mutate(c_sum = cumsum(num_movies), CDF = (c_sum/last(c_sum)) * 100) %>%
  ggplot() +
  geom_line(aes(x = rank, y = CDF))

```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
ratings %>%
  group_by(user_id) %>%
  summarize(mean_rating = mean(rating), num_ratings = n())

```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
#ratings %>%
#  mutate(date = as.Date(as.POSIXct(timestamp, origin="1970-01-01"))) %>%
#  group_by(date) %>%
#  summarize(num_ratings = n()) %>%
#  ggplot() +
#  geom_line(aes(x = date, y = num_ratings)) +
#  scale_y_log10()

ratings %>%
  group_by(user_id) %>%
  summarize(num_ratings = n()) %>%
  filter(num_ratings < quantile(num_ratings, .99)) %>%
  ggplot() +
  geom_histogram(aes(x = num_ratings)) +
  scale_x_log10()

```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).
 
movie_pop <- ratings %>%
  group_by(movie_id)%>%
  summarize(num_ratings = n()) %>%
  arrange(desc(num_ratings)) %>%
  mutate(rank = row_number())

ratings_pop <- inner_join(ratings, movie_pop, by = 'movie_id')

satisfaction_90 <- ratings_pop %>%
  group_by(user_id) %>%
  summarize(cutoff = quantile(rank, .9)) %>%
  group_by(cutoff) %>%
  summarize(num_users = n()) %>%
  arrange(cutoff) %>%
  mutate(c_sum = cumsum(num_users)) %>%
  mutate(frac_users = c_sum/last(c_sum)) %>%
  mutate(origin = "Satisfaction 90")

satisfaction_100 <- ratings_pop %>%
  group_by(user_id) %>%
  summarize(cutoff = max(rank)) %>%
  group_by(cutoff) %>%
  summarize(num_users = n()) %>%
  arrange(cutoff) %>%
  mutate(c_sum = cumsum(num_users)) %>%
  mutate(frac_users = c_sum/last(c_sum)) %>%
  mutate(origin = "Satisfaction 100")
  
bind_rows(satisfaction_90, satisfaction_100) %>%
  ggplot() +
  geom_line(aes(x=cutoff, y=frac_users, color=origin))

```
