---
title: "predict_citibike"
author: "Brian Hernandez"
date: "June 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(glmnet)

load('trips.RData')

trips_with_weather <- inner_join(trips, weather)

```

#Feature Selection

``` {r feature_selection}

# Plot to understand the data a little better
trips_with_weather %>%
  mutate(month = month(ymd)) %>%
  group_by(ymd, month) %>%
  summarize(count = n()) %>%
  ggplot() +
  geom_point(aes(x = day(ymd), y = count)) + 
  facet_wrap(~ day)

# Creating new features to regress over
trips_full <- trips_with_weather %>%
  group_by(ymd, tmin, tmax, prcp, snow, snwd) %>%
  summarize(trips = n()) %>%
  ungroup() %>%
  mutate(day_of_week = weekdays(ymd)) %>%
  mutate(month = as.factor(month(ymd))) %>%
  mutate(prev_prcp = lag(prcp)) %>%
  mutate(prev_snow = lag(snow)) %>%
  mutate(prev_snwd = lag(snwd)) %>%
  mutate(prev_trips = lag(trips))

# Creating the training and testing dataset
train <- trips_full[1:(nrow(trips_full)*.8),]
train <- train %>% filter(!is.na(prev_prcp))
test <- anti_join(trips_full, train)

# Creating the model matrices for the lasso calculations
x <- model.matrix(trips ~ poly(prcp, 5), train)
y <- train$trips

# Creating the model with lambda = lambda.1se
cvfit_1se <- cv.glmnet(x, y)
coef(cvfit_1se, s = "lambda.1se")

# Creating the model with lambda = lambda.min
cvfit_min <- cv.glmnet(x, y)
coef(cvfit_min, s = "lambda.min")
  
```

``` {r prediction_model}

# Creating new features to regress over
trips_full <- trips_with_weather %>%
  group_by(ymd, tmin, tmax, prcp, snow, snwd) %>%
  summarize(trips = n()) %>%
  ungroup() %>%
  mutate(day_of_week = weekdays(ymd)) %>%
  mutate(month = as.factor(month(ymd))) %>%
  mutate(prev_prcp = lag(prcp)) %>%
  mutate(prev_snow = lag(snow)) %>%
  mutate(prev_snwd = lag(snwd))

# Creating the training and testing dataset
train <- trips_full[1:(nrow(trips_full)*.8),]
train <- train %>% filter(!is.na(prev_prcp))
test <- anti_join(trips_full, train)
test <- test %>% filter(!is.na(prev_prcp))

polynomial_power <- rep(0, 5)
curr_max <- 0
for(i1 in 1:4){
  for(i2 in 1:4){
    for(i3 in 1:4){
      for(i4 in 1:4){
        for(i5 in 1:4){
          curr_model <- lm(formula = trips ~ day_of_week * poly(tmin, i1) * poly(tmax, i2) * poly(prcp, i3) * poly(snwd, i4) * poly(prev_snwd, i5), data = train)
          test$predictions <- predict(curr_model, newdata = test)
          curr_rsquared <- cor(test$predictions, test$trips)^2
          if(curr_rsquared > curr_max){
            polynomial_power[1] <- i1
            polynomial_power[2] <- i2
            polynomial_power[3] <- i3
            polynomial_power[4] <- i4
            polynomial_power[5] <-i5
            curr_max <- curr_rsquared
          }
        }
      }
    }
  }
}

curr_model <- lm(formula = trips ~ poly(tmin, 1) * poly(tmax, 3) * poly(prcp, 1) * poly(snwd, 1) * poly(prev_snwd, 1), data = train)
test$predictions <- predict(curr_model, newdata = test)
cor(test$predictions, test$trips)^2

```
